# ------------------------------------------------------------
# Sample hosts.yml file
#
# Entries for Linux, Microsoft Windows, and z/OS.
# Entries for CICS, DB2, z/OSMF managed by the z/OS host.
# ------------------------------------------------------------
all:
  children:
    linux:
      hosts:
        linux01:
          ansible_host: xxx.xxx.xxx.xxx
          ansible_user: admin
          ansible_ssh_private_key_file: pathtofile
          ansible_python_interpreter: /usr/bin/python3

    windows:
      hosts:
        windows01:
          ansible_host: xxx.xxx.xxx.xxx
          ansible_user: Administrator

# Uncomment next line if you use public/private keys          
#          ansible_ssh_private_key_file: pathtofile
# Uncomment next line if you use an encrypted password
#          ansible_password: "{{ vault_windows_password }}"
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore

    zos:
      hosts:
        zos01:
          ansible_host: zos.example.com # or IP address
          ansible_user: ZOSUSER
# Uncomment next line if you use public/private keys          
#          ansible_ssh_private_key_file: pathtofile
# Uncomment next line if you use an encrypted password
#          ansible_password: "{{ vault_zos_password }}"
          ansible_connection: ssh
          ansible_port: 22
          ansible_python_interpreter: /usr/lpp/IBM/cyp/v3r12/pyz

    cics:
      hosts:
        zos01:
          cics_region_name: CICS01
          cics_applid: CICS01
          cics_cmci_host: zos.example.com # or IP address
          cics_cmci_port: 1490
          cics_cmci_protocol: https
          cics_cmci_user: CICSUSER
          cics_cmci_password: "{{ vault_cics_cmci_password }}"

    db2:
      hosts:
        zos01:
          db2_subsystem: DB2A
          db2_location: DB2A
          db2_sql_port: 446
          db2_admin_user: DB2USER
          db2_admin_password: "{{ vault_db2_password }}"

    zosmf:
      hosts:
        zosmf01:
          zmf_host: zosmf.example.com # or IP address
          zmf_port: 443
          zmf_user: ZOSMFUSER
          zmf_password: "{{ vault_zosmf_password }}"
          zmf_scheme: https
          zosmf_system_nickname: ZOS1
